services:
  # Backend API Service
  - type: web
    name: dungeonforge-api
    env: python
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: AIRIA_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: STACK_AI_API_URL
        sync: false
      - key: STACK_AI_API_KEY
        sync: false

  # Frontend Static Site
  - type: web
    name: dungeonforge-frontend
    env: static
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false


